#!/bin/bash

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

if [ $# -eq 0 ]; then
    echo "Must specify an argument"
    echo "Usage: ${0} <password>"
    exit 1
fi
TORPASSWORD=`docker run --rm --name torpasswd lncm/tor:0.4.7.7 --hash-password $1`
echo "Add to your torrc config"
echo ""
echo "HashedControlPassword ${TORPASSWORD}"
